version: "2.1"
services:
  server:
    build: .
    container_name: server
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - nodeServerSync:/server
  db:
    container_name: db
    image: mongo
    command: mongod --smallfiles
    volumes:
      - ./mongo/db:/data/db
    # ports:
    #   - "27017:27017"
    healthcheck:
      test: ["CMD", "echo", "show dbs", "|", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  nodeServerSync:
    external: true


